### ISSUE TITLE
Bash Shell: Using the Command Line

### ISSUE THREAD

**Issue by PipGrylls** [Southampton-RSG-Training/dirac-bash-command-line-old#1]
Connecting to remote HPC system [Alpha, Internally Reviewed]
Moving around and looking at things [Alpha, Internally Reviewed]
Writing and reading files [Alpha, Internally Reviewed]
Wildcards and pipes [Alpha, Internally Reviewed]

**Comment by PipGrylls** [comment]
All @EdwardRSE, all light edit

**Comment by PipGrylls** [comment]
4 days effort

**Comment by phillybroadbent** [comment]
Why use a cluster?
•	In ‘the rest of this lesson’ – could be unclear what ‘these types of resources’ refers to as it’s been a while since HPC was mentioned

Connecting to the remote HPC system
•	Creating an SSH key – ‘SSH keys are an alternative method for authentication to obtain access to remote computing systems’, what are they an alternative to? 
•	Creating an SSH key – What is PEM? (Is it privacy enhanced mail?)
•	What is passphrase derivation?
•	Logging onto the system – details of HPC system missing
•	Login worked with id__ed25519 rather than key__ed25519
•	The output for the prompt isn’t there

Moving around and looking at things
•	The previous lesson says that the prompt will indicate whether you should be working from the local computer [local]$ or the remote system `` but this isn’t carried through into this lesson
•	‘When typing commands, either from these lessons or from other sources, do not type the prompt, only the commands that follow it.’ – might be better before the learner has created the ssh key and connected to the HPC system using the CLI
•	I found it a bit unclear whether the commands should be run on the remote or local system
•	Relative path resolution – couldn’t find the backup files referred to in the correct answer (4) so number 1 would have been my answer (../backup: No such file or directory).  The next exercise links on from this and therefore was a bit confusing too.

Writing and reading files
•	The instructions guide the learner to create draft.txt but not to write anything in it but then using `cat` displays some text as it’s contents which could be confusing.
•	Looking at files - I couldn’t download the file ' https://southampton-rsg-training.github.io/dirac-essentials/files/bash-lesson.tar.gz’ (I got the error ‘HTTP request sent, awaiting response... 404 Not Found’) tar

Wildcards and pipes
•	I couldn’t download  https://southampton-rsg-training.github.io/dirac-essentials/files/bash-lesson.tar.gz so I tried out the commands from this lesson on another folder of data
•	Chaining commands together – the pipe operator is introduced twice (in the 1st and 3rd paragraphs)

**Comment by steve-crouch** [comment]
Reviewed and completed, and material ported to new repo using training infrastructure - https://github.com/Southampton-RSG-Training/dirac-bash-command-line
